[build]
  publish = "dist"
  command = "bash -c 'curl -fsSL https://bun.sh/install | bash && export PATH=\"$HOME/.bun/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\" && bun install && bun run build'"

[context.production.environment]
  BUN_INSTALL = "$HOME/.bun"
  PATH = "$HOME/.bun/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  PYTHON_VERSION = "3.11"
