[build]
  command = "bash build.sh"
  publish = ".next"
  functions = ".netlify/functions"

[context.production.environment]
  BUN_INSTALL = "$HOME/.bun"
  PATH = "$HOME/.bun/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.11"
